### ISSUE TITLE
On updating subscription_item quantity, invoice immediately value is not working

### ISSUE THREAD

**Issue by sandy-tpp** [deanpcmad/lemonsqueezy#8]
I tried the below code to update the quantity. The quantity is updated in the item, but the invoice is not processed immediately.

```body = {
          data: {
            type: "subscription-items",
            id: id.to_s,
            attributes: {
              quantity: quantity,
              invoice_immediately: true,
            }
          }
}
response = LemonSqueezy::Client.patch_request("subscription-items/#{id}", body: body.to_json)
LemonSqueezy::SubscriptionItem.new(response.body["data"]) if response.success?

**Comment by deanpcmad** [comment]
Again, this looks like an issue with the Lemon Squeezy API? Have you tried contacting them about these 2 issues?

**Comment by sandy-tpp** [comment]
Have raised a ticket, will keep the thread updated.

**Comment by deanpcmad** [comment]
Closing this as there's been no update and I don't believe it's an issue with this library
