### ISSUE TITLE
On Updating the Subscription plan, the quantity resets to 1

### ISSUE THREAD

**Issue by sandy-tpp** [deanpcmad/lemonsqueezy#9]
I'm updating a Subscription with planA and quantity x to planB. The plan, variant update happens and invoice is processed, but the quantity resets to 1.

```
LemonSqueezy::Subscription.change_plan(id: subscription_id, plan_id: plan_id, variant_id: var_id, invoice_immediately: true)
```

**Comment by deanpcmad** [comment]
This sounds like an issue with the LemonSqueezy API?

**Comment by sandy-tpp** [comment]
Yes, Have raised a ticket, will keep the thread updated.

**Comment by deanpcmad** [comment]
@sandy-tpp any update from them?

**Comment by deanpcmad** [comment]
Closing this as there's been no update and I don't believe it's an issue with this library
